# Generated by Django 2.0.2 on 2018-02-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
            ],
        ),
    ]
